SELECT * FROM USER_TABLES;

SELECT * FROM USER_TAB_COLS;

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_CLUSTERS;

SELECT * FROM USER_SEGMENTS;

SELECT * FROM USER_TS_QUOTAS;

SELECT * FROM RECYCLEBIN;



-- Total blocks used (cannot exceed 1740 for Exercise 1)
SELECT BLOCKS FROM USER_TS_QUOTAS WHERE TABLESPACE_NAME = 'USERS';

-- Blocks used for each table
SELECT SEGMENT_NAME, BLOCKS FROM USER_SEGMENTS;

-- TABLE propierties
SELECT table_name, num_rows, avg_row_len FROM USER_TABLES;
