all:cuantosHay cuentaA ple_compartido ple_no_compartido redirecciona redirecciona2 redirecciona3

cuantosHay:cuantosHay.c
	gcc -o cuantosHay cuantosHay.c
cuentaA:cuentaA.c
	gcc -o cuentaA cuentaA.c
ple_compartido:ple_compartido.c
	gcc -o ple_compartido ple_compartido.c
ple_no_compartido:ple_no_compartido.c
	gcc -o ple_no_compartido ple_no_compartido.c
redirecciona2:redirecciona2.c
	gcc -o redirecciona2 redirecciona2.c
redirecciona3:redirecciona3.c
	gcc -o redirecciona3 redirecciona3.c
redirecciona:redirecciona.c
	gcc -o redirecciona redirecciona.c
clean:
	rm -rf cuantosHay cuentaA ple_compartido ple_no_compartido redirecciona redirecciona2 redirecciona3
