all: ocreat tamanyo_con_lseek otrunc read_con_lseek ve_a_x 1_de_2 lectura_con_buffer lee_enteros_escribe_chars escribe_enteros

ocreat:ocreat.c
	gcc -o ocreat ocreat.c
tamanyo_con_lseek:tamanyo_con_lseek.c 
	gcc -o tamanyo_con_lseek tamanyo_con_lseek.c
otrunc:otrunc.c
	gcc -o otrunc otrunc.c
read_con_lseek:read_con_lseek.c
	gcc -o read_con_lseek read_con_lseek.c
ve_a_x:ve_a_x.c 
	gcc -o ve_a_x ve_a_x.c
1_de_2:1_de_2.c
	gcc -o 1_de_2 1_de_2.c
lectura_con_buffer:lectura_con_buffer.c
	gcc -o lectura_con_buffer lectura_con_buffer.c
lee_enteros_escribe_chars:lee_enteros_escribe_chars.c
	gcc -o lee_enteros_escribe_chars lee_enteros_escribe_chars.c
escribe_enteros:escribe_enteros.c
	gcc -o escribe_enteros escribe_enteros.c
clean: 
	rm -rf ocreat otrunc tamanyo_con_lseek read_con_lseek ve_a_x 1_de_2 lectura_con_buffer lee_enteros_escribe_chars escribe_enteros
